package_name: docs
version: 0.1dev
license: MIT
summary: Documentation Assistant for various documentation projects
homepage: https://github.com/tradej/doc-assistant
authors: [Tomas Radej <tradej@redhat.com>]
dependencies: [common_args, github]
description: |
    This Assistant contains facilities to create documents in various languages
    and convert them to HTML. More features to come.
